name: Rust - Clippy

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # selecting a toolchain either by action or manual `rustup` calls should happen
    # before the plugin, as the cache uses the current rustc version as its cache key
    - run: rustup toolchain install nightly 

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "clippy"

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
